# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-MirrorDir
version:      0.03
version_from: lib/Net/MirrorDir.pm
installdirs:  site
requires:
    Net::FTP:                      

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
